### ISSUE TITLE
Question about the camera.npz

### ISSUE THREAD

**Issue by xjchao7** [jby1993/SelfReconCode#11]
When I processed my own video data, I found I need to prepare camera.npz. I would like to know how to obtain this file, do you need checkerboard calibration? I found that VideoAvatar also needs camera parameters to obtain the pose reconstruction. 

Looking forward to your reply.

Thx~

**Comment by jby1993** [comment]
The estimated SMPL parameters and camera intrinsic are needed for SelfRecon. VideoAvatar can estimate them for a video. Or you can use easymocap to do the initialization, but you need to convert the data yourself.

**Comment by jby1993** [comment]
Checkerboard calibration can supply more accurate camera parameters. SelfRecon can still work with estimated camera intrinsic with simple methods, such as estimation based on image size.

**Comment by xjchao7** [comment]
> Checkerboard calibration can supply more accurate camera parameters. SelfRecon can still work with estimated camera intrinsic with simple methods, such as estimation based on image size.

Amazing! Thank you very much.
