### ISSUE TITLE
Question on inference

### ISSUE THREAD

**Issue by xjchao7** [jby1993/SelfReconCode#14]
Hi~Thank you for your work. When I infer the model on custom dataset, it has following error
![error1](https://user-images.githubusercontent.com/105781839/178172435-04528fe8-f260-464d-8994-c40c4e2cb134.png)

Could you please tell my why this error "unwished error n_inv mask:(1:10000)" will occured. How could I deal with it?

Thank you very much.

**Comment by jby1993** [comment]
You can ignore it if the number is small. Noninvertible Jacob matrices of some sample points cause this.

**Comment by Xianjin111** [comment]
> You can ignore it if the number is small. Noninvertible Jacob matrices of some sample points cause this.

Thank you very much!
