### ISSUE TITLE
run on my own data

### ISSUE THREAD

**Issue by surheaven** [jby1993/SelfReconCode#15]
hello, when i run code from vedioavatar to get the keypoints.hdf5,the code is
![image](https://user-images.githubusercontent.com/89247297/178265583-140b86f3-e39e-40e0-aeda-980dd867bb7f.png)
but i find the data'size from the openpose is 75 not the 54.
i don't know whether it is right.

**Comment by jby1993** [comment]
Check the openpose documentation. I think it is due to a different configuration.

**Comment by surheaven** [comment]
hello, I found that my attempt to run vedioavatar failed, so I asked if there would be a big problem if I didn't use reconstructed_poses.hdf5?

**Comment by jby1993** [comment]
You can give an initial SMPL estimation with your own method, but need to figure out how to use it for SelfRecon. The camera coordinate frame of SelfRecon follows pytorch3d's configuration.

**Comment by surheaven** [comment]
Hello, I am sorry to bother you again. I was doing the "python generate_boxes.py" operation and found that "len(pose_entries)" are nearly all 0, which causes most of my rect files to be empty. I would like to ask what is the reason for this result?
![image](https://user-images.githubusercontent.com/89247297/178720180-08c83c9d-35c9-410f-9663-4954899277a9.png)

**Comment by surheaven** [comment]
When I run the infer of my own data, the final color and mesh results are normal, but the defmesh is all blank, why is this?
![0](https://user-images.githubusercontent.com/89247297/180694523-062915b9-2267-4ef8-94e8-630a83037f5d.png)

**Comment by jby1993** [comment]
Maybe the camera configuration is wrong, not see the object

**Comment by surheaven** [comment]
I can't understand why use new camera like this to render the defmesh.
newcameras=RectifiedPerspectiveCameras(focals,princeple_ps,torch.tensor([[[-1.,0.,0.],[0.,1.,0.],[0.,0.,-1.]]],device=device).repeat(N,1,1),newTs.repeat(N,1),image_size=[(W, H)]).to(device)
Why R is set as [[[-1.,0.,0.],[0.,1.,0.],[0.,0.,-1.]]] and newTs is set as
