### ISSUE TITLE
How to get such texture.png?

### ISSUE THREAD

**Issue by xjchao7** [jby1993/SelfReconCode#16]
Hi, Thank you for your work. I would like to ask how to get the similar texture.png as follows:
![texture](https://user-images.githubusercontent.com/105781839/178976607-457c56ba-9d91-4c12-96d9-b43af66e4ad8.png)
I utilize my texture.png,but the result is not good.
![texture](https://user-images.githubusercontent.com/105781839/178976855-73bcfac4-7585-4a0f-8b9b-4ff0b76b3ff5.png)
 So couldyou please show me more steps to get the similar texture.png

Thank you very much.

**Comment by jby1993** [comment]
What is your parameterization method? You can use blender to mark some seams manually and then uv unwarp to get more regular parameterization. Or you can find some mesh cut algorithm to find the seams automaticly.

**Comment by Xianjin111** [comment]
Thank you for your answer.

**Comment by surheaven** [comment]
Can you recommend some mesh cut algorithm? Thank you!

**Comment by jby1993** [comment]
You can try [optcut](https://github.com/liminchen/OptCuts), [GreedyCut](https://ustc-gcl-f.github.io/#GreedyCut).
