### ISSUE TITLE
motion sequences

### ISSUE THREAD

**Issue by gqbay** [jby1993/SelfReconCode#2]
First of all, thank you so much for releasing! 

Would you answer me please:
According to information on your page below in attached screenshot I can use monocular video with 1 person who makes some movement, apply your SelfRecon to the video and receive animated mesh that matching the shape of the real person on the video? Then I can use it in 3D software like Blender? 
Am I correctly understanding? Actually this pipeline is exactly what I need. 

Best regards

![image](https://user-images.githubusercontent.com/65506709/172045024-6b4a061b-074e-48cd-988d-06075f56f890.png)

**Comment by jby1993** [comment]
Before running SelfRecon, You need to supply initial SMPL tracking, human segmentation, and predicted normals(optional). Then SelfRecon can reconstruct a better mesh tracking sequence based on the initialization. The releasing code is for self-rotating sequence and does not assure the quality for general movements.

**Comment by gqbay** [comment]
Got it, thanks for replying 🙏
Will the results of mesh tracking sequence will be some .OBJ files? Or any other 3D file format?

**Comment by jby1993** [comment]
It can be saved as obj. To save memory, I save the vertices position of per frame as npy and save the template mesh as obj or ply.

**Comment by gqbay** [comment]
Understood! I think I should take some time to go deep in the project! Thanks a lot for opportunity!
