### ISSUE TITLE
Quantitative Result

### ISSUE THREAD

**Issue by JcqJcq** [jby1993/SelfReconCode#20]
Hi Boyi,

Thanks for your great work and awesome codebase. I am interested in leveraging your synthetic data as a benchmark to make comparison e.g. your table 1, but I didn't see the ground truth 3D model. Would you please also release the ground truth scans?

**Comment by jby1993** [comment]
I upload the synthetic template GT(synthetic_GT.zip) and my aligned reconstruction(synthetic_regist.zip) in the Dataset's link of README.

**Comment by JcqJcq** [comment]
Many thanks for your speedy help!
