### ISSUE TITLE
关于获取pixel 的ray 的问题

### ISSUE THREAD

**Issue by lingtengqiu** [jby1993/SelfReconCode#22]
关于获取camrea ray 上我有一个问题,
```
	def view_rays(self,ps,cam_id=0):
		rays=torch.zeros_like(ps)
		rays[:,0]=-ps[:,0]/self.focal_length[cam_id,0]+ps[:,2]*self.principal_point[cam_id,0]/self.focal_length[cam_id,0]
```
根据你们代码,他获取ray 的方式是上述的函数但是根据pytorch 3d 投影公式 \
screen_x = X * fx / Z + px
在你设Z = screen_z 后,
上述公式不是等于
X = px * screen_z / fx - (screen_x * screen_z) /fx
那么上述代码是不是应该改为 
```
	def view_rays(self,ps,cam_id=0):
		rays=torch.zeros_like(ps)
		rays[:,0]=-ps[:,0]* ps[:,2]/self.focal_length[cam_id,0]+ps[:,2]*self.principal_point[cam_id,0]/self.focal_length[cam_id,0]
```

**Comment by jby1993** [comment]
你的公式 是已经齐次化了，screen_z就是1. 通过下面的公式算就好了，后面再normalize成单位向量
-fx 0 px   X     screen_x
0 -fy py * Y =  screen_y
0  0  1     Z     screen_z

**Comment by lingtengqiu** [comment]
> 你的公式 是已经齐次化了，screen_z就是1. 通过下面的公式算就好了，后面再normalize成单位向量 -fx 0 px X screen_x 0 -fy py * Y = screen_y 0 0 1 Z screen_z
非常感谢!!!!
