### ISSUE TITLE
How to obtain the T-pose reconstruction?

### ISSUE THREAD

**Issue by xjchao7** [jby1993/SelfReconCode#27]
Hi~

If I want to obtain the T-pose reconstruction, whether I shoud change the initial sdf to t-pose?
Because when I use the T-pose image as input, the output is still A-pose.

How to obtain th T-pose reconstruction?

Thank you very much.

**Comment by xjchao7** [comment]
I have found it. Thank you very much.

**Comment by surheaven** [comment]
Can you tell me where you found it? Thank you very much!
