### ISSUE TITLE
Questions about the reproduction of quantitative results.

### ISSUE THREAD

**Issue by SongYupei** [jby1993/SelfReconCode#34]
Thank you very much for the open-source data of this work. I want to reproduce the evaluation results of your paper on simulation data, but I can't seem to find this part of the evaluation code. Can you provide the relevant source code? Thank you very much!
![image](https://user-images.githubusercontent.com/42504875/198175110-55d57a44-3c3d-4250-aa0a-c0b0f633edf8.png)

**Comment by jby1993** [comment]
You can try the rigid registration [method](https://github.com/yaoyx689/Fast-Robust-ICP)
