### ISSUE TITLE
为什么经过deform变换之后，整个model会旋转过来

### ISSUE THREAD

**Issue by surheaven** [jby1993/SelfReconCode#37]
![image](https://user-images.githubusercontent.com/89247297/225794282-81a4aa26-b643-4474-84fc-899ef555c101.png)
是因为tmpmesh是在最初的世界坐标系，而defmesh是在camera坐标系的嘛？selfrecon代码只输入了camera内参，为什么能构建出camera坐标系和tmpmesh世界坐标系之间的关系呢？而且为什么是左右上下颠倒的呢？

**Comment by jby1993** [comment]
利用smpl姿态参数和平移会变到相机坐标系，相机系是按照pytorch3d的设置来的

**Comment by surheaven** [comment]
我看到代码里通过pytorch3d的相机来渲染每一帧的图像，我应该如何设置camera来渲染tempmesh呢？

**Comment by surheaven** [comment]
我看到代码里通过pytorch3d的相机来渲染defmesh，我应该如何设置camera来渲染tmpmesh呢？是可以用pytorch3d的正交相机直接渲染得到？还是将tmpmesh变换到相机坐标系，用对应的相机渲染？

**Comment by jby1993** [comment]
正确设置好相机位置朝向就能渲染

**Comment by surheaven** [comment]
感谢
