### ISSUE TITLE
[error] cd ../MCAcc/cuda python setup.py install 

### ISSUE THREAD

**Issue by surheaven** [jby1993/SelfReconCode#5]
running install
running bdist_egg
running egg_info
writing interplate.egg-info/PKG-INFO
writing top-level names to interplate.egg-info/top_level.txt
writing dependency_links to interplate.egg-info/dependency_links.txt
reading manifest file 'interplate.egg-info/SOURCES.txt'
writing manifest file 'interplate.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
building 'GridSamplerMine' extension
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-oYYDrU/python2.7-2.7.17=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/home/user/.local/lib/python2.7/site-packages/torch/include -I/home/user/.local/lib/python2.7/site-packages/torch/include/torch/csrc/api/include -I/home/user/.local/lib/python2.7/site-packages/torch/include/TH -I/home/user/.local/lib/python2.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python2.7 -c GridSamplerMine.cpp -o build/temp.linux-x86_64-2.7/GridSamplerMine.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=GridSamplerMine -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
GridSamplerMine.cpp:1:10: fatal error: ATen/native/GridSampler.h: No such file or directory
 #include <ATen/native/GridSampler.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by jby1993** [comment]
It is a PyTorch version issue.

**Comment by surheaven** [comment]
I use "conda env create -f environment.yml" to create environment and PyTorch version is 1.10.2.

**Comment by jby1993** [comment]
Your linked torch is in python2.7, you need to check it out.
