### ISSUE TITLE
How to install openmesh

### ISSUE THREAD

**Issue by xjchao7** [jby1993/SelfReconCode#8]
Thank you for your perfect work. When I run the inference code. I met "ModuleNotFoundError: No module named 'openmesh'".  Do you know how to quickly install OpenMesh on Linux.

Thank you very much.

**Comment by MySTerY1747** [comment]
OpenMesh is a python module, so to install it just do:

```
pip install openmesh
```

If you don't have pip installed, run:

```
sudo apt install python3-pip
```
And try re-running the previous command.

**Comment by xjchao7** [comment]
I think it's probably because I use Docker to install the environment. Thanks again.
