### ISSUE TITLE
Some questions about the results

### ISSUE THREAD

**Issue by xjchao7** [jby1993/SelfReconCode#9]
Thank you for your perfect work. I have some questions as follows:
1. Does getting the mesh of different people require everyone to retrain?
2. Why inferenc time is slow. which step is very time-consuming?

Thanks again.

**Comment by jby1993** [comment]
1. Yes
2. Getting the color of neural rendering is slow.

**Comment by xjchao7** [comment]
> 1. Yes
> 2. Getting the color of neural rendering is slow.

Got it. Thank you very much.
